# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# minecraft_version=1.21.11
# loader_version=0.18.1
# fabric_version=0.141.2+1.21.11

# Mod Properties
mod_version=0.2.4
maven_group=org.blackum
archives_base_name=BlackAddons

dev.kikugie.stonecutter.hard_mode=true
